
-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 22:43:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecomerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecomerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecomerce` DEFAULT CHARACTER SET utf8 ;
USE `ecomerce` ;

-- -----------------------------------------------------
-- Table `ecomerce`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `descricao_produto` VARCHAR(100) NOT NULL,
  `preco_produto` FLOAT NOT NULL,
  `genero_produto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomerce`.`imagensProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`imagensProduto` (
  `id_imagens_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_imagem` VARCHAR(45) NOT NULL,
  `imagem_produto` LONGBLOB NOT NULL,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_imagens_produto`),
  INDEX `fk_imagensProduto_produto_idx` (`produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_imagensProduto_produto`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `ecomerce`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomerce`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(50) NOT NULL,
  `sobrenome_cliente` VARCHAR(50) NOT NULL,
  `cpf_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomerce`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`enderecos` (
  `id_enderecos` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cliente_cpf_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_enderecos`),
  INDEX `fk_enderecos_cliente1_idx` (`cliente_cpf_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_cliente1`
    FOREIGN KEY (`cliente_cpf_cliente`)
    REFERENCES `ecomerce`.`cliente` (`cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomerce`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `cliente_cpf_cliente` VARCHAR(45) NOT NULL,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_carrinho`),
  INDEX `fk_carrinho_cliente1_idx` (`cliente_cpf_cliente` ASC) VISIBLE,
  INDEX `fk_carrinho_produto1_idx` (`produto_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_cliente1`
    FOREIGN KEY (`cliente_cpf_cliente`)
    REFERENCES `ecomerce`.`cliente` (`cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `ecomerce`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Inserir um cliente
INSERT INTO `ecomerce`.`cliente` (`nome_cliente`, `sobrenome_cliente`, `cpf_cliente`)
VALUES ('João', 'Silva', '123.456.789-02');

-- Inserir um endereço para o cliente João
INSERT INTO `ecomerce`.`enderecos` (`rua`, `bairro`, `cidade`, `cliente_cpf_cliente`)
VALUES ('Rua A', 'Centro', 'Cidade A', '123.456.789-02');

-- Inserir outro cliente
INSERT INTO `ecomerce`.`cliente` (`nome_cliente`, `sobrenome_cliente`, `cpf_cliente`)
VALUES ('Maria', 'Santos', '987.654.321-02');

-- Inserir um endereço para o cliente Maria
INSERT INTO `ecomerce`.`enderecos` (`rua`, `bairro`, `cidade`, `cliente_cpf_cliente`)
VALUES ('Rua B', 'Bairro B', 'Cidade B', '987.654.321-02');

-- Inserir outro cliente
INSERT INTO `ecomerce`.`cliente` (`nome_cliente`, `sobrenome_cliente`, `cpf_cliente`)
VALUES ('Alessandro', 'C. Santos', '987.782.321-02');

-- Inserir um endereço para o cliente Maria
INSERT INTO `ecomerce`.`enderecos` (`rua`, `bairro`, `cidade`, `cliente_cpf_cliente`)
VALUES ('Rua Primeiro de Novembro', 'Bandeira do Almada', 'Itajuipe', '987.782.321-02');

SELECT 
    c.nome_cliente,
    c.sobrenome_cliente,
    e.rua,
    e.bairro,
    e.cidade
FROM 
    `ecomerce`.`cliente` c
JOIN 
    `ecomerce`.`enderecos` e ON c.cpf_cliente = e.cliente_cpf_cliente;

-- Inserir um item no carrinho para um cliente específico
INSERT INTO `ecomerce`.`carrinho` (`cliente_cpf_cliente`, `produto_id_produto`)
VALUES ('123.456.789-01', 1); -- Substitua pelo CPF real do cliente e pelo ID do produto desejado

-- Inserir outro item no carrinho para um cliente diferente
INSERT INTO `ecomerce`.`carrinho` (`cliente_cpf_cliente`, `produto_id_produto`)
VALUES ('987.654.321-01', 2); -- Substitua pelo CPF real do cliente e pelo ID do produto desejado

SELECT
    c.id_carrinho,
    cl.nome_cliente,
    p.nome_produto,
    p.descricao_produto,
    p.preco_produto
FROM
    `ecomerce`.`carrinho` c
JOIN
    `ecomerce`.`cliente` cl ON c.cliente_cpf_cliente = cl.cpf_cliente
JOIN
    `ecomerce`.`produto` p ON c.produto_id_produto = p.id_produto;

select * from cliente;


SELECT produto.*, imagensProduto.*
FROM ecomerce.produto
LEFT JOIN ecomerce.imagensProduto ON produto.id_produto = imagensProduto.produto_id_produto;


use ecomerce;
select * from cliente;
INSERT INTO carrinho (cliente_cpf_cliente, produto_id_produto) VALUES ('987.782.321-02', 1);
SELECT carrinho.*, produto.*, imagensproduto.*  FROM carrinho INNER JOIN produto ON carrinho.produto_id_produto = produto.id_produto
INNER JOIN imagensproduto
ON produto.id_produto = id_imagens_produto;

select * from carrinho ;
DELETE FROM carrinho WHERE produto_id_produto = 16;
SELECT
  c.cliente_cpf_cliente,
  SUM(p.preco_produto) AS total_carrinho
FROM
  carrinho c
JOIN
  produto p ON c.produto_id_produto = p.id_produto
WHERE
  c.cliente_cpf_cliente = '0';
